CREATE TABLE [dbo].[Addresses]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Street] NVARCHAR(100) NOT NULL, 
    [City] NVARCHAR(50) NOT NULL, 
    [Zip] NVARCHAR(50) NOT NULL, 
    [State] NVARCHAR(50) NOT NULL
)
